---
apiVersion: v1
kind: Secret
metadata:
  name: ai-service-credentials
  namespace: ai-service
  labels:
    owner: excel-addin
    component: ai-service
    managed-by: kubernetes
  annotations:
    rotation-schedule: 90d
    last-rotated: ${LAST_ROTATION_TIMESTAMP}
    secret-type: api-credentials
    encryption: aes-256
type: Opaque
data:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  AI_SERVICE_AUTH_TOKEN: ${AI_SERVICE_AUTH_TOKEN}
---
apiVersion: v1
kind: Secret
metadata:
  name: core-service-auth
  namespace: core-service
  labels:
    owner: excel-addin
    component: core-service
    managed-by: kubernetes
  annotations:
    rotation-schedule: 90d
    last-rotated: ${LAST_ROTATION_TIMESTAMP}
    secret-type: service-auth
    encryption: aes-256
type: Opaque
data:
  JWT_SECRET: ${JWT_SECRET}
  SERVICE_API_KEY: ${SERVICE_API_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: data-service-db-credentials
  namespace: data-service
  labels:
    owner: excel-addin
    component: data-service
    managed-by: kubernetes
  annotations:
    rotation-schedule: 30d
    last-rotated: ${LAST_ROTATION_TIMESTAMP}
    secret-type: database-credentials
    encryption: aes-256
type: Opaque
data:
  DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
  REDIS_PASSWORD: ${REDIS_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-service-ssl
  namespace: gateway-service
  labels:
    owner: excel-addin
    component: gateway-service
    managed-by: kubernetes
  annotations:
    rotation-schedule: 365d
    last-rotated: ${LAST_ROTATION_TIMESTAMP}
    secret-type: ssl-certificates
    encryption: aes-256
type: Opaque
data:
  SSL_PRIVATE_KEY: ${SSL_PRIVATE_KEY}
  SSL_CERTIFICATE: ${SSL_CERTIFICATE}