---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-service-account
  namespace: ai-service
  labels:
    app: excel-addin
    component: ai
    environment: ${ENV}
    tier: backend
    version: ${VERSION}
    managed-by: kubernetes
    auto-rotate: enabled
  annotations:
    security.alpha.kubernetes.io/automated-rotation: enabled
    monitoring.excel-addin.io/audit-level: detailed
    compliance.excel-addin.io/last-review: ${LAST_REVIEW_DATE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-service-account
  namespace: core-service
  labels:
    app: excel-addin
    component: core
    environment: ${ENV}
    tier: backend
    version: ${VERSION}
    managed-by: kubernetes
    auto-rotate: enabled
  annotations:
    security.alpha.kubernetes.io/automated-rotation: enabled
    monitoring.excel-addin.io/audit-level: detailed
    compliance.excel-addin.io/last-review: ${LAST_REVIEW_DATE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-service-account
  namespace: data-service
  labels:
    app: excel-addin
    component: data
    environment: ${ENV}
    tier: backend
    version: ${VERSION}
    managed-by: kubernetes
    auto-rotate: enabled
  annotations:
    security.alpha.kubernetes.io/automated-rotation: enabled
    monitoring.excel-addin.io/audit-level: detailed
    compliance.excel-addin.io/last-review: ${LAST_REVIEW_DATE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service-account
  namespace: gateway-service
  labels:
    app: excel-addin
    component: gateway
    environment: ${ENV}
    tier: frontend
    version: ${VERSION}
    managed-by: kubernetes
    auto-rotate: enabled
  annotations:
    security.alpha.kubernetes.io/automated-rotation: enabled
    monitoring.excel-addin.io/audit-level: detailed
    compliance.excel-addin.io/last-review: ${LAST_REVIEW_DATE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-service-account
  namespace: monitoring
  labels:
    app: excel-addin
    component: monitoring
    environment: ${ENV}
    tier: observability
    version: ${VERSION}
    managed-by: kubernetes
    auto-rotate: enabled
  annotations:
    security.alpha.kubernetes.io/automated-rotation: enabled
    monitoring.excel-addin.io/audit-level: comprehensive
    compliance.excel-addin.io/last-review: ${LAST_REVIEW_DATE}