---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: core-service
  labels:
    app: excel-addin
    component: core
    security-zone: restricted
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: excel-addin
      component: core
  template:
    metadata:
      labels:
        app: excel-addin
        component: core
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: core-service
        image: $(REGISTRY)/excel-addin/core-service:$(TAG)
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
          name: http-api
        envFrom:
        - configMapRef:
            name: core-service-config
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /startup
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - excel-addin
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfied: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: excel-addin
            component: core
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: core-service
  labels:
    app: excel-addin
    component: core
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http-api
    protocol: TCP
    name: http-api
  selector:
    app: excel-addin
    component: core